2025-02-11 09:44:04.742 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration winix which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ac_infinity which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.745 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lock_code_manager which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.746 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.746 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.747 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration toyota_na which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.747 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration llama_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_easy_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration extended_openai_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.749 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ab_gateway which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.749 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.749 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration govee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:04.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-11 09:44:07.030 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accessed lovelace_data['resources'] instead of lovelace_data.resources at custom_components/browser_mod/mod_view.py, line 59: resources = hass.data["lovelace"]["resources"]. This will stop working in Home Assistant 2026.2, please report it to the author of the 'browser_mod' custom integration
2025-02-11 09:44:07.109 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.181 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.240 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.283 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.368 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.415 WARNING (SyncWorker_0) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.462 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.511 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.564 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.626 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.676 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.769 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.844 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.918 WARNING (SyncWorker_0) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:07.973 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:44:11.165 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from tplink_easy_smart, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'tplink_easy_smart' custom integration
2025-02-11 09:44:16.895 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.wyze_cam_print_cam_bitrate: 0 (range 1.0 - 1000.0)
2025-02-11 09:44:16.895 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.wyze_cam_print_cam_fps: 0 (range 1.0 - 30.0)
2025-02-11 09:44:16.896 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.wyze_cam_grow_cam_bitrate: 0 (range 1.0 - 1000.0)
2025-02-11 09:44:16.896 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.wyze_cam_grow_cam_fps: 0 (range 1.0 - 30.0)
2025-02-11 09:44:17.045 ERROR (MainThread) [homeassistant.components.mqtt.client] Exception in _state_message_received when handling msg on 'wyzebridge/print-cam/alarm': '0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/entity.py", line 1470, in _message_callback
    msg_callback(msg)
    ~~~~~~~~~~~~^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/siren.py", line 218, in _state_message_received
    json_payload = json_loads_object(payload)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 60, in json_loads_object
    raise ValueError(f"Expected JSON to be parsed as a dict got {type(value)}")
ValueError: Expected JSON to be parsed as a dict got <class 'int'>

2025-02-11 09:44:17.057 ERROR (MainThread) [homeassistant.components.mqtt.client] Exception in _state_message_received when handling msg on 'wyzebridge/grow-cam/alarm': '0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/entity.py", line 1470, in _message_callback
    msg_callback(msg)
    ~~~~~~~~~~~~^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/siren.py", line 218, in _state_message_received
    json_payload = json_loads_object(payload)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 60, in json_loads_object
    raise ValueError(f"Expected JSON to be parsed as a dict got {type(value)}")
ValueError: Expected JSON to be parsed as a dict got <class 'int'>

2025-02-11 09:44:50.021 WARNING (MainThread) [alexapy.helpers] alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f55828dd010>,), {'max_record_size': 10}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2025-02-11 09:44:50.880 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set last_fertigation_str = states('input_datetime.last_fertigation_time') %} {% if last_fertigation_str %}  # Check if last_fertigation time is set
  {% set last_fertigation = as_datetime(last_fertigation_str) %}
  {% set readings_str = states('sensor.reserviorsensor_reservoir_depth') %}
  {% if readings_str is string %}
    {% set readings = readings_str.split(',') | map('float') %}
    {% set filtered_readings = [] %}
    {% for i in range(readings | length) %}
      {% set reading_time_str = state_attr('sensor.reserviorsensor_reservoir_depth', 'last_updated') %}
      {% if reading_time_str %}
        {% set reading_time = as_datetime(reading_time_str) %}
        {% if reading_time > last_fertigation %}
          {% set filtered_readings = filtered_readings + [readings[i]] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if filtered_readings | length > 0 %}
      {{ filtered_readings | average }}
    {% else %}
      unavailable
    {% endif %}
  {% else %}
    unavailable
  {% endif %}
{% else %}
  unavailable
{% endif %}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 643, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2756, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 7, in top-level template code
TypeError: object of type 'generator' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 760, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 645, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: object of type 'generator' has no len()
2025-02-11 09:44:50.884 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: object of type 'generator' has no len()') while processing template 'Template<template=({% set last_fertigation_str = states('input_datetime.last_fertigation_time') %} {% if last_fertigation_str %}  # Check if last_fertigation time is set
  {% set last_fertigation = as_datetime(last_fertigation_str) %}
  {% set readings_str = states('sensor.reserviorsensor_reservoir_depth') %}
  {% if readings_str is string %}
    {% set readings = readings_str.split(',') | map('float') %}
    {% set filtered_readings = [] %}
    {% for i in range(readings | length) %}
      {% set reading_time_str = state_attr('sensor.reserviorsensor_reservoir_depth', 'last_updated') %}
      {% if reading_time_str %}
        {% set reading_time = as_datetime(reading_time_str) %}
        {% if reading_time > last_fertigation %}
          {% set filtered_readings = filtered_readings + [readings[i]] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if filtered_readings | length > 0 %}
      {{ filtered_readings | average }}
    {% else %}
      unavailable
    {% endif %}
  {% else %}
    unavailable
  {% endif %}
{% else %}
  unavailable
{% endif %}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.current_interval_average'
2025-02-11 09:44:59.351 WARNING (MainThread) [switchbot.devices.device] CE-92-9F-AE-8D-CD (CE:92:9F:AE:8D:CD): Device unexpectedly disconnected; RSSI: -79
2025-02-11 09:45:09.470 WARNING (MainThread) [switchbot.devices.device] CE-92-9F-AE-8D-CD (CE:92:9F:AE:8D:CD): Device unexpectedly disconnected; RSSI: -79
2025-02-11 09:45:14.219 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.290 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.294 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.323 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.334 WARNING (SyncWorker_0) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.425 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.458 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.502 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.507 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.549 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.573 WARNING (SyncWorker_0) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.578 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.585 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:45:14.618 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.216 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.257 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.296 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.305 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.324 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.431 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.453 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.509 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.515 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.552 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.576 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.580 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.587 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:46:14.614 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.203 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.252 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.293 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.302 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.324 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.411 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.448 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.498 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.507 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.530 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.589 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.595 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.604 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:47:14.617 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.213 WARNING (SyncWorker_9) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.254 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.297 WARNING (SyncWorker_14) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.301 WARNING (SyncWorker_13) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.319 WARNING (SyncWorker_18) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.424 WARNING (SyncWorker_7) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.454 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.502 WARNING (SyncWorker_0) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.510 WARNING (SyncWorker_16) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.553 WARNING (SyncWorker_22) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.572 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.576 WARNING (SyncWorker_15) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.591 WARNING (SyncWorker_23) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2025-02-11 09:48:14.616 WARNING (SyncWorker_21) [py.warnings] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.137'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

